version: '3'

services:
  # to enable the management plugin (web)
  # docker exec fz_rabbitmq rabbitmq-plugins enable rabbitmq_management
  rabbitmq:
    hostname: fz_rabbitmq
    container_name: fz_rabbitmq
    image: rabbitmq:alpine
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_ERLANG_COOKIE=fzcookie
    ports:
      - "5672:5672"
      - "15672:15672"

  webserver:
    container_name: fz_webserver
    image: fz/webserver:latest
    build:
      context: .
      dockerfile: ./.docker/webserver/file.dockerfile
    ports:
      - "8888:8888"

  apigateway:
    container_name: fz_apigateway
    image: fz/apigateway:latest
    build:
      context: .
      dockerfile: ./.docker/apigateway/file.dockerfile
    ports:
      - "8090:8090"

  money:
    container_name: fz_money
    image: fz/money:latest
    build:
      context: .
      dockerfile: ./.docker/money/file.dockerfile

  users:
    container_name: fz_users
    image: fz/users:latest
    build:
      context: .
      dockerfile: ./.docker/users/file.dockerfile

  eventstore:
    container_name: fz_eventstore
    image: fz/eventstore:latest
    build:
      context: .
      dockerfile: ./.docker/eventstore/file.dockerfile




